//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_var_6.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Activities()
        {
            this.Activity_Zhury = new HashSet<Activity_Zhury>();
        }
    
        public int id { get; set; }
        public string activity { get; set; }
        public int id_meropriyatiye { get; set; }
        public string day { get; set; }
        public string start_time { get; set; }
        public Nullable<int> id_moderator { get; set; }
        public Nullable<int> id_winner { get; set; }
    
        public virtual Meropriyatiya Meropriyatiya { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Zhury> Activity_Zhury { get; set; }
    }
}
