//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_var_6.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meropriyatiya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meropriyatiya()
        {
            this.Activities = new HashSet<Activities>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> id_city { get; set; }
        public string event_picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual Cities Cities { get; set; }
    }
}
