//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_var_6.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Activities = new HashSet<Activities>();
            this.Activities1 = new HashSet<Activities>();
            this.Activity_Zhury = new HashSet<Activity_Zhury>();
        }
    
        public int id { get; set; }
        public string fio { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> id_country { get; set; }
        public string phone_number { get; set; }
        public string password { get; set; }
        public string photo { get; set; }
        public Nullable<int> gender { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<int> napravlenie { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity_Zhury> Activity_Zhury { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual Napravleniya Napravleniya { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
